name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install nox
      run: pip install nox
    - name: run nox
      run: nox